version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<TASK_DEFINITION>"
        LoadBalancerInfo:
          ContainerName: "<CONTAINER NAME>"
          ContainerPort: "<CONTAINER PORT, e.g.80>"